### ISSUE TITLE
Slow desktop switching due to specific slow windows

### ISSUE THREAD

**Issue by Whathecode** [StevenHouben/ABC#8]
I was experiencing a consistent slow (about 4s) desktop switch, but only to the home activity, so I decided to investigate which particular process/window was causing the delay.

I pinned it down to exactly one application causing the delay:
netsession_win.exe, which is the Akamai NetSession Client by Akamai Technologies, Inc.

Now we can easily ignore this through VdmSettings, however, what is it that causes this delay? In case there is nothing we can do about it, can we at least detect the applications causing these delays automatically?

This particular one [is a rather suspicious app]( http://www.hanselman.com/blog/CSIMyComputerWhatIsNetsessionwinexeFromAkamaiAndHowDidItGetOnMySystem.aspx).

**Comment by dominkomin** [comment]
The problem is probably caused by slow message parsing. It would be really hard to investigate it further and say exactly why messages are parsed slowly- there could be many reasons, like implementation details, different execution platforms, drivers etc.

We approach this issue by providing a mechanism that sends a message when unresponsive/slow window was detected. Decision what to do with problematic window is left to the API consumer (he is able to ignore or keep it).  

It would be beneficial to make a log of those slow applications and approach them individually (so that API consumer does not have to decide each time to ignore or keep).
